{
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "# 📊 Canva‑AI Slide Generator (single‑image)\n",
        "\n",
        "This notebook:\n",
        "1️⃣ Accepts a **text prompt**.\n",
        "2️⃣ Calls **OpenAI DALL·E** (or any compatible image‑generation API) to create **one image**.\n",
        "3️⃣ Builds a **PowerPoint slide** (`.pptx`) with the image as a separate, editable element.\n",
        "4️⃣ The resulting PPTX can be **imported into Canva** – the slide becomes fully editable inside Canva.\n",
        "\n",
        "---\n",
        "▶️ **Requirements**:\n",
        "- An OpenAI API key (or alternative image‑generation endpoint).\n",
        "- `python-pptx` for PowerPoint creation.\n",
        "- `requests` for downloading the image.\n",
        "\n",
        "You can replace the DALL·E block with any other service – just return a direct image URL."
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "# ------------------------------------------------------------\n",
        "# 1️⃣ Install required libraries (run once)\n",
        "# ------------------------------------------------------------\n",
        "%pip install --quiet openai python-pptx requests"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "# ------------------------------------------------------------\n",
        "# 2️⃣ Imports & API configuration\n",
        "# ------------------------------------------------------------\n",
        "import os\n",
        "import requests\n",
        "from pathlib import Path\n",
        "\n",
        "from pptx import Presentation\n",
        "from pptx.util import Inches, Pt\n",
        "\n",
        "# ---- OpenAI (DALL·E) configuration ---------------------------------\n",
        "# Put your OpenAI key in an environment variable for safety.\n",
        "# e.g. in a terminal: export OPENAI_API_KEY='sk-...'\n",
        "openai_api_key = os.getenv('OPENAI_API_KEY')\n",
        "if not openai_api_key:\n",
        "    raise RuntimeError('Set the OPENAI_API_KEY environment variable before running the notebook')\n",
        "\n",
        "import openai\n",
        "openai.api_key = openai_api_key"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "# ------------------------------------------------------------\n",
        "# 3️⃣ Helper: generate a single image from a prompt\n",
        "# ------------------------------------------------------------\n",
        "def generate_image(prompt: str, size: str = \"1024x1024\") -> Path:\n",
        "    \"\"\"Generate an image using OpenAI DALL·E.\n",
        "\n",
        "    Args:\n",
        "        prompt: Text description.\n",
        "        size: One of \"256x256\", \"512x512\", \"1024x1024\" (default).\n",
        "\n",
        "    Returns:\n",
        "        Path to the downloaded PNG file.\n",
        "    \"\"\"\n",
        "    # 1️⃣ Call the API\n",
        "    response = openai.Image.create(\n",
        "        prompt=prompt,\n",
        "        n=1,\n",
        "        size=size,\n",
        "        response_format=\"url\",\n",
        "    )\n",
        "\n",
        "    image_url = response[\"data\"][0][\"url\"]\n",
        "    print(f\"🖼️ Image URL: {image_url}\")\n",
        "\n",
        "    # 2️⃣ Download the image\n",
        "    img_data = requests.get(image_url).content\n",
        "    out_path = Path(\"generated.png\")\n",
        "    out_path.write_bytes(img_data)\n",
        "    print(f\"✅ Image saved to {out_path.resolve()}\")\n",
        "    return out_path\n",
        "\n",
        "# ------------------------------------------------------------\n",
        "# Example usage (uncomment & run the cell to test)\n",
        "# ------------------------------------------------------------\n",
        "# prompt_text = \"A futuristic city skyline at sunset, cyber‑punk style\"\n",
        "# img_path = generate_image(prompt_text)\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "# ------------------------------------------------------------\n",
        "# 4️⃣ Build a PowerPoint slide with the generated image\n",
        "# ------------------------------------------------------------\n",
        "def create_pptx_with_image(\n",
        "    image_path: Path,\n",
        "    output_path: Path = Path(\"slide_with_image.pptx\"),\n",
        "    slide_width_in: float = 10,  # inches (default PowerPoint width)\n",
        "    slide_height_in: float = 5.625,  # inches (default PowerPoint height)\n",
        "    margin_in: float = 0.5,\n",
        ") -> Path:\n",
        "    \"\"\"Create a PPTX containing a single slide with *image_path*.\n",
        "\n",
        "    The image is added as an independent picture shape so you can move/resize it\n",
        "    later in PowerPoint, Google Slides, or after importing the file into Canva.\n",
        "    \"\"\"\n",
        "\n",
        "    prs = Presentation()\n",
        "    # Set custom slide dimensions if you want – here we keep the defaults\n",
        "    prs.slide_width = Inches(slide_width_in)\n",
        "    prs.slide_height = Inches(slide_height_in)\n",
        "\n",
        "    # Add a blank layout (index 6 is usually the blank slide)\n",
        "    blank_layout = prs.slide_layouts[6]\n",
        "    slide = prs.slides.add_slide(blank_layout)\n",
        "\n",
        "    # ------- Insert the image -----------------------------------\n",
        "    # Compute a nice default size: fill most of the slide while respecting margins\n",
        "    max_width = prs.slide_width - Inches(2 * margin_in)\n",
        "    max_height = prs.slide_height - Inches(2 * margin_in)\n",
        "\n",
        "    # Load the image dimensions (requires Pillow)\n",
        "    from PIL import Image as PilImage\n",
        "    with PilImage.open(image_path) as img:\n",
        "        img_w, img_h = img.size\n",
        "    # Convert pixel size to inches (96 DPI is the PPTX default)\n",
        "    img_w_in = img_w / 96\n",
        "    img_h_in = img_h / 96\n",
        "\n",
        "    # Scale proportionally to fit inside max_width/max_height\n",
        "    scale = min(max_width / Inches(img_w_in), max_height / Inches(img_h_in), 1.0)\n",
        "    final_w = Inches(img_w_in) * scale\n",
        "    final_h = Inches(img_h_in) * scale\n",
        "\n",
        "    # Center the image on the slide\n",
        "    left = (prs.slide_width - final_w) / 2\n",
        "    top = (prs.slide_height - final_h) / 2\n",
        "\n",
        "    slide.shapes.add_picture(str(image_path), left, top, width=final_w, height=final_h)\n",
        "\n",
        "    # Save the deck\n",
        "    prs.save(output_path)\n",
        "    print(f\"💾 PPTX saved to {output_path.resolve()}\")\n",
        "    return output_path\n",
        "\n",
        "# ------------------------------------------------------------\n",
        "# Example usage (run after you have generated an image)\n",
        "# ------------------------------------------------------------\n",
        "# pptx_path = create_pptx_with_image(img_path)\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "# ------------------------------------------------------------\n",
        "# 5️⃣ Full pipeline – ONE cell you can run end‑to‑end\n",
        "# ------------------------------------------------------------\n",
        "def generate_slide_from_prompt(prompt: str):\n",
        "    \"\"\"One‑stop helper: generate image → create PPTX → return paths.\n",
        "    Returns (image_path, pptx_path).\n",
        "    \"\"\"\n",
        "    img_path = generate_image(prompt)\n",
        "    pptx_path = create_pptx_with_image(img_path)\n",
        "    return img_path, pptx_path\n",
        "\n",
        "# ---- Example ------------------------------------------------\n",
        "# Uncomment the lines below, replace the prompt, and run.\n",
        "# prompt_example = \"A cute red panda wearing glasses, flat‑style illustration\"\n",
        "# img_file, pptx_file = generate_slide_from_prompt(prompt_example)\n",
        "# print(\"✅ Done! Image →\", img_file, \"| PPTX →\", pptx_file)\n"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "## 📥 What to do after the notebook runs\n",
        "\n",
        "1. **Download `slide_with_image.pptx`** from the notebook’s file browser.\n",
        "2. **Open Canva → Create a design → Import file** and select that PPTX.\n",
        "3. Canva will convert each PowerPoint slide into an editable Canva page. The image you generated will be a separate draggable element – you can add text, stickers, backgrounds, etc.\n",
        "\n",
        "That’s it – you have an *AI‑generated image* in a *fully editable slide* inside Canva!\n",
        "\n",
        "---\n",
        "### 🔧 Customising the output\n",
        "- **Image size** – change the `size` argument in `generate_image` (e.g. `\"512x512\"`).\n",
        "- **Slide dimensions** – modify `slide_width_in` / `slide_height_in` in `create_pptx_with_image` (use inches or cm via `Cm`).\n",
        "- **Positioning** – edit the `margin_in` or directly set `left`, `top` values.\n",
        "- **Alternative AI back‑ends** – replace the `openai.Image.create` block with any service that returns a direct image URL (e.g. Replicate, Stability AI, etc.).\n",
        "\n",
        "Happy creating! 🎨"
      ]
    }
  ],
  "metadata": {
    "kernelspec": {
      "display_name": "Python 3",
      "language": "python",
      "name": "python3"
    },
    "language_info": {
      "name": "python",
      "version": "3.11"
    }
  },
  "nbformat": 4,
  "nbformat_minor": 5
}